version: '3'
services:
  mariadb: 
    container_name: mariadb_container
    build: ./requirements/mariadb/
    ports:
      - 3306:3306
    networks:
      - 42incept
    env_file: .env
    restart: always
    volumes: 
      - dbdata:/var/lib/mysql
  wordpress: 
    container_name: wordpress_container
    build: ./requirements/wordpress/
    ports:
      - 9000:9000
    networks:
      - 42incept
    env_file: .env
    restart: always
    volumes:
      - wpdata:/var/www/wordpress/
    depends_on:
      - mariadb
  nginx: 
    container_name: nginx_container
    build: ./requirements/nginx/
    ports:
      - 443:443
    networks:
      - 42incept
    env_file: .env
    restart: always
    volumes:
      - wpdata:/var/www/wordpress/
    depends_on:
      - wordpress
networks:
  42incept:
    driver: bridge
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_HOST_VOLUME_PATH}
      o: bind
  wpdata:
    driver: local
    driver_opts:
      type: none
      device: ${WP_HOST_VOLUME_PATH}
      o: bind
